package com.gome.gmhx.jbpm;

public class HXPositionMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JBPM4_POSITION_MAPPING.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JBPM4_POSITION_MAPPING.jbpm_role_code
     *
     * @mbggenerated
     */
    private String jbpmRoleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JBPM4_POSITION_MAPPING.jbpm_role_name
     *
     * @mbggenerated
     */
    private String jbpmRoleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JBPM4_POSITION_MAPPING.system_position_id
     *
     * @mbggenerated
     */
    private String systemPositionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JBPM4_POSITION_MAPPING.id
     *
     * @return the value of JBPM4_POSITION_MAPPING.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JBPM4_POSITION_MAPPING.id
     *
     * @param id the value for JBPM4_POSITION_MAPPING.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JBPM4_POSITION_MAPPING.jbpm_role_code
     *
     * @return the value of JBPM4_POSITION_MAPPING.jbpm_role_code
     *
     * @mbggenerated
     */
    public String getJbpmRoleCode() {
        return jbpmRoleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JBPM4_POSITION_MAPPING.jbpm_role_code
     *
     * @param jbpmRoleCode the value for JBPM4_POSITION_MAPPING.jbpm_role_code
     *
     * @mbggenerated
     */
    public void setJbpmRoleCode(String jbpmRoleCode) {
        this.jbpmRoleCode = jbpmRoleCode == null ? null : jbpmRoleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JBPM4_POSITION_MAPPING.jbpm_role_name
     *
     * @return the value of JBPM4_POSITION_MAPPING.jbpm_role_name
     *
     * @mbggenerated
     */
    public String getJbpmRoleName() {
        return jbpmRoleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JBPM4_POSITION_MAPPING.jbpm_role_name
     *
     * @param jbpmRoleName the value for JBPM4_POSITION_MAPPING.jbpm_role_name
     *
     * @mbggenerated
     */
    public void setJbpmRoleName(String jbpmRoleName) {
        this.jbpmRoleName = jbpmRoleName == null ? null : jbpmRoleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JBPM4_POSITION_MAPPING.system_position_id
     *
     * @return the value of JBPM4_POSITION_MAPPING.system_position_id
     *
     * @mbggenerated
     */
    public String getSystemPositionId() {
        return systemPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JBPM4_POSITION_MAPPING.system_position_id
     *
     * @param systemPositionId the value for JBPM4_POSITION_MAPPING.system_position_id
     *
     * @mbggenerated
     */
    public void setSystemPositionId(String systemPositionId) {
        this.systemPositionId = systemPositionId == null ? null : systemPositionId.trim();
    }
}