package com.gome.gmhx.dao.jbpm;

import com.gome.gmhx.jbpm.HXPositionMapping;

public interface HXPositionMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_POSITION_MAPPING
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_POSITION_MAPPING
     *
     * @mbggenerated
     */
    int insert(HXPositionMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_POSITION_MAPPING
     *
     * @mbggenerated
     */
    int insertSelective(HXPositionMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_POSITION_MAPPING
     *
     * @mbggenerated
     */
    HXPositionMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_POSITION_MAPPING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HXPositionMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_POSITION_MAPPING
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HXPositionMapping record);
}